### ISSUE TITLE
a confused about performConcurrentWorkOnRoot , looking for your help !

### ISSUE THREAD

**Issue by chrislol98** [BetaSu/big-react#38]
![QQ截图20230513144101](https://github.com/BetaSu/big-react/assets/90550975/3329610c-0d36-4561-bb1f-97d0f9901960)
  如果更新一个高优先级的任务，那么会触发update,执行ensureRootIsScheduled，在里面已经加入了performConcurrentWorkOnRoot。
  然后在图中也就是上一次的performConcurrentWorkOnRoot又执行了一次ensureRootIsScheduled。那么performConcurrentWorkOnRoot是不是被重复添加了两次？
![QQ截图20230513144318](https://github.com/BetaSu/big-react/assets/90550975/31b50c42-99ab-4d30-b206-070b67b2802c)

**Comment by samllbin** [comment]
同问，求解
